services:
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - traefik
  api:
    build: ./backend

    environment:
      - STORAGE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=todo
      - MYSQL_PWD=DitIsGoed
      - MYSQL_DB=todo
    networks:
      - traefik

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - MYSQL_ROOT_PASSWORD=DitIsGoed
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=DitIsGoed
      - MYSQL_DATABASE=todo
    networks:
      - traefik
volumes:
  db-volume:
networks:
  traefik:
    external: true
    name: traefik
