FROM nginx:1.27

# Kopieer je configuratie direct in de image
COPY ./default.conf /etc/nginx/conf.d/default.conf

# Kopieer je frontend bestanden direct in de image
COPY ./frontend /usr/share/nginx/html

EXPOSE 80