services:
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - traefik
  api:
    build: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=${USER}
      - MYSQL_PWD=${PASS}
      - MYSQL_DB=${DB}
    networks:
      - traefik

  db:
    image: mysql
    volumes:
      - db-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_DATABASE=${DB}
    networks:
      - traefik
volumes:
  db-volume:
networks:
  traefik:
    external: true
    name: traefik
